version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: franchises
      MYSQL_USER: franchise_user
      MYSQL_PASSWORD:
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7.2
    container_name: redis

  app:
    build: .
    container_name: franchises-app
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/franchises
      SPRING_R2DBC_USERNAME: franchise_user
      SPRING_R2DBC_PASSWORD:
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080"